[Description]
students = 20
instruction = """This experiment includes several games. In each game you will be asked to select one of two alternatives.
At the end of the experiment one of the games will be randomly drawn (all the games are equally likely to
be drawn), and the alternative selected in this game will be realized.
Your payoff for the experiment will be the outcome (in Sheqels) of this game.
Good luck!
"""

trial_template = """Please choose between:

[{H} with probability {ph} {L} otherwise (with probability {pl})]  |   [{m} with certainty]
"""

[E-sampling]
students = 100
instruction = """This experiment includes several games. Each game includes two stages: The sampling stage and the
choice stage.
At the choice stage (the second stage) you will be asked to select once between two virtual decks cards
(two buttons). Your choice will lead to a random draw of one card from this deck, and the number written on
the card will be the ‘‘game’s outcome.’’
During the sampling stage (the first stage) you will be able to sample the two decks. When you feel that
you have sampled enough press the ‘‘choice stage’’ key to move to the choice stage.
At the end of the experiment one of the games will be randomly drawn (all the games are equally likely to
be drawn). Your payoff for the experiment will be the outcome (in Sheqels) of this game.
Good luck!"""
sampling_stage = """
Sampling Stage
[{L}]  | [{R}]

[To The Real Game Stage]"""

game_state = """Game State: {game_state}
{Done | }
"""

[E-repeating]
students = 100
instruction = """This experiment includes several games. Each game includes several trials. You will receive a message
before the beginning of each game.
In each trial you will be asked to select one of two buttons. Each press will result in a payoff that will be
presented on the selected button.
At the end of the experiment one of the trials will be randomly drawn (all the trials are equally likely to be
drawn). Your payoff for the experiment will be the outcome (in Sheqels) of this trial.
Good luck!"""

trial_template = """Payoff from current trial {payoff}"""